[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "builddrone"
version = "0.2.0"
description = "Modular build framework"
authors = [{ name = "Andreas Sekulski" }]
readme = "README.md"
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/Nepitwin/Builddrone"
Repository = "https://github.com/Nepitwin/Builddrone"
PyPI = "https://pypi.org/project/builddrone/"


[project.optional-dependencies]
dev = [
    "build",
    "twine",
    "pytest",
    "black",
    "isort",
    "pylint"
]


[tool.setuptools.packages.find]
where = ["src"]


[tool.isort]
profile = "black"
line_length = 88


[tool.pytest.ini_options]
pythonpath = [
    "src"
]


[tool.pylint.main]
init-hook = "import sys; sys.path.insert(0, 'src')"
